### ISSUE TITLE
read failed, socket might closed or timeout, read ret: -1

### ISSUE THREAD

**Issue by ravi2143** [tcd93/flutter-pos#15]
E/BThermalPrinterPlugin: read failed, socket might closed or timeout, read ret: -1
    java.io.IOException: read failed, socket might closed or timeout, read ret: -1
        at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:758)
        at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:772)
        at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:404)
        at id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin.lambda$connect$1$BlueThermalPrinterPlugin(BlueThermalPrinterPlugin.java:544)
        at id.kakzaki.blue_thermal_printer.-$$Lambda$BlueThermalPrinterPlugin$Ahw9MM_9K6f9UCVqtrNy_jHybcU.run(Unknown Source:6)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

I am getting this error while printing.

**Comment by tcd93** [comment]
That seems like a bug related to older Android device, what printer were you running on?

I've pushed a [fix](https://github.com/tcd93/blue_thermal_printer/commit/7a32c20478d54414185cbbcf14786ff4c38bdf06), run `flutter pub upgrade` and try again
